### PR TITLE
fix(nemesis): get bytes total for correct network device

### PR DESCRIPTION
**Pull request by juliayakovlev**
If test runs with 2 network interfaces configuration, 'disrupt_network_random_interruptions' nemesis fails with error:
```
File '/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py', line 3376, in get_rate_limit_for_network_disruption
return '{}{}'.format(random.randrange(min_limit, max_limit), rate_limit_suffix) ValueError: empty range for randrange() (0, 0, 0)
```

It happened because 'node_network_receive_bytes_total' is reported on device that broadcast_address is configured on it.
Now the device is set hardcoded to 'eth0'.

Failed test: https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=21961db0-285c-4b84-a4da-4d70be149e06

### Testing

- [x] [longevity-50gb-two-interfaces-test](https://argus.scylladb.com/test/b08fa1c7-ae96-4a5b-be2d-98db30813a00/runs?additionalRuns[]=0cc74a59-788d-47a1-a7ba-fb7994ca7af7)

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

File: sdcm/provision/network_configuration.py [hunk 1]
```diff
@@ -89,6 +89,15 @@ def interface_ipv6_address(self):
         else:
             return None
 
+    @property
+    def device(self):
+        # Depend on network configuration:
+        # - "eth0" - if broadcast_address.nic = 0
+        # - "eth1" - if broadcast_address.nic = 1
+        if broadcast_address_config := [conf for conf in self.scylla_network_config if conf["address"] == "broadcast_address"]:
+            return f"eth{broadcast_address_config[0]['nic']}"
```
Comment (fruch) [inline sdcm/provision/network_configuration.py:98]: It might be better if we could get the interface names from the node,and hardcode/template it. on some instance types we might get other device names.

Comment (juliayakovlev) [reply sdcm/provision/network_configuration.py:98]: @fruch 
I get device id from ec2 client. 
```
{'Attachment': 
{'AttachTime': datetime.datetime(2024, 10, 7, 7, 30, 56, tzinfo=tzutc()), 
'AttachmentId': 'eni-attach-0bb1a575eec8d29e5', 
'DeleteOnTermination': True, 
'DeviceIndex': 1, 
'Status': 'attached', 'NetworkCardIndex': 0}, 
'Description': '', 'Groups': [{'GroupName': 'SCT-2-sg', 'GroupId': 'sg-0691c61126d99dd41'}], 'Ipv6Addresses': [{'Ipv6Address': '2a05:d018:12e3:f003:27cd:a725:49cb:939c'}], 
'MacAddress': '0a:e9:43:52:54:3f', 'NetworkInterfaceId': 'eni-0746041ce753fc3bb', 'OwnerId': '797456418907', 'PrivateDnsName': 'ip-10-4-14-86.eu-west-1.compute.internal', 'PrivateIpAddress': '10.4.14.86', 'PrivateIpAddresses': [{'Primary': True, 'PrivateDnsName': 'ip-10-4-14-86.eu-west-1.compute.internal', 'PrivateIpAddress': '10.4.14.86'}], 'SourceDestCheck': True, 'Status': 'in-use', 'SubnetId': 'subnet-09976342f9d62db9f', 'VpcId': 'vpc-05caf4736ea5af013', 'InterfaceType': 'interface'}
```

Or get device name from `/etc/netplan/50-cloud-init.yaml` by `macaddress`.
```
network:
    ethernets:
        ens5:
            dhcp4: true
            dhcp4-overrides: &id001
                route-metric: 100
            dhcp6: true
            dhcp6-overrides: *id001
            match:
                macaddress: 0a:ec:c0:45:cb:dd
            set-name: ens5
        ens6:
            dhcp4: true
            dhcp4-overrides: &id002
                route-metric: 200
            dhcp6: true
            dhcp6-overrides: *id002
            match:
                macaddress: 0a:e9:43:52:54:3f
            set-name: ens6

```

File: sdcm/cluster_aws.py [hunk 2]
```diff
@@ -470,10 +470,23 @@ def __str__(self):
             " | %s" % self.ipv6_ip_address if self.test_config.IP_SSH_CONNECTIONS == "ipv6" else "",
             self._dc_info_str())
 
+    def network_configuration(self):
+        network_config = self.remoter.sudo("cat /etc/netplan/50-cloud-init.yaml").stdout.strip()
```
Comment (fruch) [inline sdcm/cluster_aws.py:474]: I would rather we pick names and mac addresses in a more cross platform way, that can fit all OSes and all backends.

Maybe something like that:
https://unix.stackexchange.com/a/445913/418687

I don't think we can count on netplan exact configuration location/name and structure.

File: sdcm/provision/network_configuration.py [hunk 3]
```diff
@@ -89,6 +91,16 @@ def interface_ipv6_address(self):
...
 
+    @property
+    def device(self):
+        # Depend on network configuration:
+        # if broadcast_address.device_name if found
+        # else "eth0"
+        if address_config := [conf for conf in self.scylla_network_config if conf["address"] == "broadcast_address"]:
+            return "".join([ni.device_name for ni in self.network_interfaces if ni.device_index == address_config[0]['nic']]) \
+                   or "eth0"
+        return "eth0"
```
Comment (fruch) [inline sdcm/provision/network_configuration.py:102]: Hardcoded default is problematic here, we should pick a default from a real existing interface.

File: sdcm/provision/network_configuration.py (hunk 1 above)
Comment (juliayakovlev) [reply sdcm/provision/network_configuration.py]: changed

File: sdcm/cluster.py [hunk 4]
```diff
@@ -357,6 +357,9 @@ def node_rack(self) -> str:
     def network_interfaces(self):
         raise NotImplementedError()
 
+    def network_configuration(self):
```
[the remark this answers is not in the document]
Comment (juliayakovlev) [reply sdcm/cluster.py:360]: fixed

File: sdcm/cluster_aws.py (hunk 2 above)
Comment (juliayakovlev) [reply sdcm/cluster_aws.py]: changed

File: sdcm/provision/network_configuration.py (hunk 3 above)
Comment (juliayakovlev) [reply sdcm/provision/network_configuration.py]: changed to "". If we did not recognized device name, do not put the value

**Comment by juliayakovlev** [comment]
@fruch @soyacz please, review

File: sdcm/provision/network_configuration.py [hunk 5]
```diff
@@ -89,6 +91,15 @@ def interface_ipv6_address(self):
...
             return None
 
+    @property
+    def device(self):
+        # Depend on network configuration:
+        # if broadcast_address.device_name if found
+        # else empty string.
+        if address_config := [conf for conf in self.scylla_network_config if conf["address"] == "broadcast_address"]:
+            return "".join([ni.device_name for ni in self.network_interfaces if ni.device_index == address_config[0]['nic']])
+        return ""
```
Comment (fruch) [inline sdcm/provision/network_configuration.py:101]: maybe we should raise exception here ? 

it means this was called for unsupported backend, isn't it ?

Comment (fruch) [reply sdcm/provision/network_configuration.py:101]: for now it's one nemesis, that can't work on any other backends.

so we are good, as long no one tries to use it and assume the wrong idea about it, in other places

**Review by fruch — DISMISSED** [review]
LGTM

File: sdcm/nemesis.py [hunk 6]
```diff
@@ -3446,6 +3448,9 @@ def disrupt_network_random_interruptions(self):  # pylint: disable=invalid-name
         if not self.target_node.install_traffic_control():
             raise UnsupportedNemesis("Traffic control package not installed on system")
 
+        if not self.target_node.scylla_network_configuration.device:
+            raise UnsupportedNemesis("The network device name is not recognized")
```
Comment (fruch) [inline sdcm/nemesis.py:3452]: I'm not sure we want to silently skip, if this wasn't working as expected.

we want to know about it, so we'll be able to fix.

File: sdcm/cluster.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (soyacz) [reply sdcm/cluster.py:360]: please add `@property` here too

File: sdcm/nemesis.py (hunk 6 above)
Comment (juliayakovlev) [reply sdcm/nemesis.py:3452]: If this exception will be raised, we will see the reason - why it was skipped. Or raise exception will be better?

File: sdcm/provision/network_configuration.py (hunk 5 above)
Comment (juliayakovlev) [reply sdcm/provision/network_configuration.py:101]: We use it for AWS only. This nemesis can be run with more then one network interface and it is supported in AWS only. So for now only AWS test will call this property

File: sdcm/cluster_aws.py [hunk 7]
```diff
@@ -470,10 +470,26 @@ def __str__(self):
...
             self._dc_info_str())
 
+    @property
+    def network_configuration(self):
+        # Output example:
+        #   0a:7b:18:de:f9:71: eth0
+        #   0a:7b:18:de:f9:72: eth1
+        ip_link_cmd = """ip -o link | awk '$2 != "lo:" {gsub(/:/,"",$2);print $17": " $2}'"""
+        network_config = self.remoter.run(ip_link_cmd).stdout.strip()
+        netplan = yaml.safe_load(network_config)
```
[the remark this answers is not in the document]
Comment (juliayakovlev) [reply sdcm/cluster_aws.py:480]: changed

File: sdcm/cluster.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (juliayakovlev) [reply sdcm/cluster.py:361]: Added @property to overrides method

File: sdcm/nemesis.py (hunk 6 above)
Comment (fruch) [reply sdcm/nemesis.py:3452]: it would be written, but no one would looks at it.

raise an exception would serve us better here.

Comment (juliayakovlev) [reply sdcm/nemesis.py]: raised `ValueError`

**Review by soyacz — APPROVED** [review]
LGTM

**Review by fruch — APPROVED** [review]
LGTM

**Comment by grzywin** [comment]
@juliayakovlev After merging this PR Scylla Operator EKS longevity tests started to fail with error below ([jenkins run](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/107/))

```
2025-02-02 01:40:42.641: (DisruptionEvent Severity.ERROR) period_type=end event_id=4f94979b-72c6-4bc7-9a37-eaa1606e44ba duration=1s: nemesis_name=NetworkRandomInterruptions target_node=Node sct-cluster-eu-north-1-rack-1-1 [10.0.3.92 | 10.0.1.41] (rack: rack-1) errors='NoneType' object has no attribute 'device'
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5501, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3579, in disrupt_network_random_interruptions
self._disrupt_network_random_interruptions_k8s(list_of_timeout_options)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3537, in _disrupt_network_random_interruptions_k8s
rate_limit: Optional[str] = self.get_rate_limit_for_network_disruption()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3515, in get_rate_limit_for_network_disruption
(self.target_node.ip_address, self.target_node.scylla_network_configuration.device)
AttributeError: 'NoneType' object has no attribute 'device'
```

I wrote [quick fix](https://github.com/scylladb/scylla-cluster-tests/commit/72da92e9cede4cc60c36d732b14cf26401a0fcd2) for it to use `eth0` network interface in case if `self.target_node.scylla_network_configuration` will be `None`. It should do the trick but maybe you have better idea how to do it properly? Can you please take a look?

**Comment by soyacz** [comment]
> @juliayakovlev After merging this PR Scylla Operator EKS longevity tests started to fail with error below ([jenkins run](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/107/))
> 
> ```
> 2025-02-02 01:40:42.641: (DisruptionEvent Severity.ERROR) period_type=end event_id=4f94979b-72c6-4bc7-9a37-eaa1606e44ba duration=1s: nemesis_name=NetworkRandomInterruptions target_node=Node sct-cluster-eu-north-1-rack-1-1 [10.0.3.92 | 10.0.1.41] (rack: rack-1) errors='NoneType' object has no attribute 'device'
> Traceback (most recent call last):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5501, in wrapper
> result = method(*args[1:], **kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3579, in disrupt_network_random_interruptions
> self._disrupt_network_random_interruptions_k8s(list_of_timeout_options)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3537, in _disrupt_network_random_interruptions_k8s
> rate_limit: Optional[str] = self.get_rate_limit_for_network_disruption()
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3515, in get_rate_limit_for_network_disruption
> (self.target_node.ip_address, self.target_node.scylla_network_configuration.device)
> AttributeError: 'NoneType' object has no attribute 'device'
> ```
> 
> I wrote [quick fix](https://github.com/scylladb/scylla-cluster-tests/commit/72da92e9cede4cc60c36d732b14cf26401a0fcd2) for it to use `eth0` network interface in case if `self.target_node.scylla_network_configuration` will be `None`. It should do the trick but maybe you have better idea how to do it properly? Can you please take a look?

Better create PR with proposed solution so we could discuss there.
Generally, I can tell you now, if you want to do it properly, upon node.init in `BaseScyllaPodContainer` assign proper value to `self.scylla_network_configuration`. See example in `AWSNode` class.

**Comment by juliayakovlev** [comment]
> @juliayakovlev After merging this PR Scylla Operator EKS longevity tests started to fail with error below ([jenkins run](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks-test/107/))
> 
> ```
> 2025-02-02 01:40:42.641: (DisruptionEvent Severity.ERROR) period_type=end event_id=4f94979b-72c6-4bc7-9a37-eaa1606e44ba duration=1s: nemesis_name=NetworkRandomInterruptions target_node=Node sct-cluster-eu-north-1-rack-1-1 [10.0.3.92 | 10.0.1.41] (rack: rack-1) errors='NoneType' object has no attribute 'device'
> Traceback (most recent call last):
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5501, in wrapper
> result = method(*args[1:], **kwargs)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3579, in disrupt_network_random_interruptions
> self._disrupt_network_random_interruptions_k8s(list_of_timeout_options)
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3537, in _disrupt_network_random_interruptions_k8s
> rate_limit: Optional[str] = self.get_rate_limit_for_network_disruption()
> File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3515, in get_rate_limit_for_network_disruption
> (self.target_node.ip_address, self.target_node.scylla_network_configuration.device)
> AttributeError: 'NoneType' object has no attribute 'device'
> ```
> 
> I wrote [quick fix](https://github.com/scylladb/scylla-cluster-tests/commit/72da92e9cede4cc60c36d732b14cf26401a0fcd2) for it to use `eth0` network interface in case if `self.target_node.scylla_network_configuration` will be `None`. It should do the trick but maybe you have better idea how to do it properly? Can you please take a look?

@grzywin thank you for informing me. I'll check it

**Comment by juliayakovlev** [comment]
@grzywin @vponomaryov 
is "eth0" the only name that always is used by the instance in EKS test?
