### PR TITLE
fix(nemesis): skip node_operations cleanups when the target node was destroyed

### PR DESCRIPTION
**Pull request by aleksbykov**
`refuse_connection_from_banned_node` registers two cleanups on the same `ExitStack`: `block_loaders_payload_for_scylla_node` is entered first, then a finalizer that calls `_remove_node_add_node`.  The finalizer always runs first - it removes the target node from the cluster, terminates the instance and calls `BaseNode.destroy()`, which sets `destroyed` and drops the remoter to `None`.

The loader-unblock cleanup then ran `scylla_node.remoter.is_up()` unconditionally and crashed with `AttributeError: 'NoneType' object has no attribute 'is_up'`, marking a disruption that had actually succeeded as failed.

This regressed in e2b38a5fc (fix for SCT-870): before it, `destroy()` kept the remoter object around and only stopped it, so `is_up()` returned False and cleanup was skipped gracefully. Restore that behaviour with an explicit `is_node_destroyed` guard - skipping is correct here, the terminated instance took its iptables rules with it. `block_scylla_ports` and `pause_scylla_with_sigstop` get the same guard: no current caller removes the node from inside those blocks, but the failure mode would be identical.

Tests: `make_mock_node` and `sudo_commands` move to `unit_tests/unit/nemesis/__init__.py` so the mock-node factory is not duplicated across the monkey conftest and two test files. The factory must pin `destroyed = False` - a bare `MagicMock` attribute is truthy, so an auto-stubbed node reads as destroyed and would make the new guards bypass the code under test, letting the assertions pass vacuously.

Fixes: SCT-920

### Testing

- [ Job is running ](https://argus.scylladb.com/tests/scylla-cluster-tests/e67c51e6-9379-4a37-a415-d1b106baea0f)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

### CODE REVIEW

**Comment by cezarmoise** [comment]
#15848 which introduced `node.destroyed` is not backported to `branch-2026.3`, so no need to backport this.

**Review by cezarmoise — APPROVED** [review]

**Comment by fruch** [comment]
@claude reivew
@coderabbitai full review

**Review by fruch — APPROVED** [review]
