### ISSUE TITLE
disrupt_toggle_audit_syslog fails due to pull 9993

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylla-cluster-tests#10127]
## Packages

Scylla version: `2025.1.0~rc2-20250216.6ee17795783f` with build-id `8fc682bcfdf0a8cd9bc106a5ecaa68dce1c63ef6`

Kernel Version: `6.8.0-1021-aws`

disrupt_toggle_audit_syslog nemesis fails due to https://github.com/scylladb/scylla-cluster-tests/pull/9993 with error:
```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5509, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1789, in disrupt_nodetool_refresh
    if shards_num > 1 and not is_tablets_feature_enabled(session=session):
TypeError: is_tablets_feature_enabled() got an unexpected keyword argument 'session'
```

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-9 (52.215.175.216 | 10.4.13.176) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-8 (63.33.243.14 | 10.4.13.2) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-7 (18.200.118.94 | 10.4.12.89) (shards: -1)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-6 (34.252.244.59 | 10.4.13.128) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-5 (54.217.209.192 | 10.4.14.247) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-4 (54.171.18.153 | 10.4.14.196) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-3 (34.243.219.232 | 10.4.13.9) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2 (34.248.77.62 | 10.4.13.125) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-15 (54.78.104.6 | 10.4.13.167) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-14 (54.72.123.34 | 10.4.14.109) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-13 (52.213.65.205 | 10.4.13.3) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-12 (3.249.63.10 | 10.4.13.108) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-11 (63.32.35.42 | 10.4.13.241) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-10 (34.249.74.137 | 10.4.14.125) (shards: 14)
- longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-1 (18.203.124.142 | 10.4.14.19) (shards: 14)

OS / Image: `ami-089e047033a16995a` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `5cce1cf5-e2d6-4904-8eeb-72cedd820cc1`
Test name: `scylla-2025.1/tier1/longevity-50gb-3days-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/55168f34125127fa1017b430422be839fff5989f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5cce1cf5-e2d6-4904-8eeb-72cedd820cc1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5cce1cf5-e2d6-4904-8eeb-72cedd820cc1)
- Show all stored logs command: `$ hydra investigate show-logs 5cce1cf5-e2d6-4904-8eeb-72cedd820cc1`

## Logs:
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-7** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-7-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-7-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-6-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-6-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-9** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-9-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-9-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-3** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-3-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-3-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-10** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-10-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-10-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-14** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-14-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-14-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-13** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-13-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-13-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2-5cce1cf5.tar.zst)
- **longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-15** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-15-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250218_141408/longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-15-5cce1cf5.tar.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2-2025-02-18_20-47-43.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20700.1739911348000000./core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20700.1739911348000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20700.1739911348000000./core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20700.1739911348000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-2-2025-02-18_20-50-42.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20952.1739911610000000./core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20952.1739911610000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20952.1739911610000000./core.scylla.106.28ac383c0fcb46d0a2990c9f495706e2.20952.1739911610000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-8-2025-02-18_21-07-46.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.945.1739912532000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.945.1739912532000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.945.1739912532000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.945.1739912532000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-8-2025-02-18_21-12-25.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1371.1739912795000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1371.1739912795000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1371.1739912795000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1371.1739912795000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-8-2025-02-18_21-16-29.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1714.1739913061000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1714.1739913061000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1714.1739913061000000./core.scylla.106.4832f6ccccb44ef1827cadc35baa3f16.1714.1739913061000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-4-2025-02-18_21-54-17.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.5a71c232e3894a6a88ad7b5bea423419.23762.1739915346000000./core.scylla.106.5a71c232e3894a6a88ad7b5bea423419.23762.1739915346000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.5a71c232e3894a6a88ad7b5bea423419.23762.1739915346000000./core.scylla.106.5a71c232e3894a6a88ad7b5bea423419.23762.1739915346000000.zst)
- **core.scylla-longevity-tls-50gb-3d-2025-1-db-node-5cce1cf5-1-2025-02-19_03-32-19.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.6b373295b75943d986bad382aaa251c9.30466.1739935624000000./core.scylla.106.6b373295b75943d986bad382aaa251c9.30466.1739935624000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.6b373295b75943d986bad382aaa251c9.30466.1739935624000000./core.scylla.106.6b373295b75943d986bad382aaa251c9.30466.1739935624000000.zst)
- **db-cluster-5cce1cf5.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/db-cluster-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/db-cluster-5cce1cf5.tar.zst)
- **sct-runner-events-5cce1cf5.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/sct-runner-events-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/sct-runner-events-5cce1cf5.tar.zst)
- **sct-5cce1cf5.log.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/sct-5cce1cf5.log.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/sct-5cce1cf5.log.tar.zst)
- **loader-set-5cce1cf5.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/loader-set-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/loader-set-5cce1cf5.tar.zst)
- **monitor-set-5cce1cf5.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/monitor-set-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/monitor-set-5cce1cf5.tar.zst)
- **ssl-conf-5cce1cf5.tar.zst** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/ssl-conf-5cce1cf5.tar.zst](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/20250219_033520/ssl-conf-5cce1cf5.tar.zst)
- **builder-5cce1cf5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/upload_20250219_033725/builder-5cce1cf5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5cce1cf5-e2d6-4904-8eeb-72cedd820cc1/upload_20250219_033725/builder-5cce1cf5.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-2025.1/job/tier1/job/longevity-50gb-3days-test/7/)
[Argus](https://argus.scylladb.com/test/d0e174b5-e3a1-4068-8fa6-b8ef0a377370/runs?additionalRuns[]=5cce1cf5-e2d6-4904-8eeb-72cedd820cc1)
</details>

**Comment by pehala** [comment]
Could this be fixed by https://github.com/scylladb/scylla-cluster-tests/pull/10116?

@jsmolar cc

**Comment by jsmolar** [comment]
> Could this be fixed by [#10116](https://github.com/scylladb/scylla-cluster-tests/pull/10116)?
> 
> [@jsmolar](https://github.com/jsmolar) cc

Yes this should be fixed and backported https://github.com/scylladb/scylla-cluster-tests/pull/10120
